services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: N8N_PORT
        value: 10000
      - key: N8N_SECURE_COOKIE
        value: false
      - key: WEBHOOK_URL
        value: https://n8n-1-gp6g.onrender.com/
      - key: EXECUTIONS_PROCESS
        value: main
